### ISSUE TITLE
Add content to Mozilla UX wiki page

### ISSUE THREAD

**Issue by mhanratty** [mozilla/community-ux#1]
https://wiki.mozilla.org/UX

**Comment by lco** [comment]
I've made updates to the page but haven't finished. How is the wiki on Mozilla going to be different from the wiki that you created on Github?

**Comment by mhanratty** [comment]
The wiki on the github can be for more in process stuff (gathering all the info) where as the wiki on Mozilla is for when we are ready to publish it out. At least, this is my thinking.
