### ISSUE TITLE
Send update to community mailling list for feedback on UX Bootcamp

### ISSUE THREAD

**Issue by vtsatskin** [mozilla/community-ux#18]
From the discussion with @mhanratty in #11, we should inform the community through our mailing list about this new bootcamp we're developing. Quoting @mhanratty:

> Awesome, love the enthusiasm! Since there aren't many folks on the github yet, maybe email the community-ux@mozilla.org and ux-team@mozilla.com lists about the idea of creating a bootcamp so people are aware and can give feedback. I would include the purpose of the bootcamp, why you are so passionate about it (i.e. as an intern this stuff was scattered everywhere or does not even exist), and a link to the webdev bootcamp for reference. You can link to the different github issues for people to get involved, learn more, and give feedback.

Information to convey:
- [ ] Purpose of bootcamp
- [ ] Why it's important
- [ ] Link to bootcamp
- [ ] What information are you looking for to start contributing?
- [ ] How to give feedback on existing sections

**Comment by jdittrich** [comment]
Is the material here open to feedback or is the Bugtracker intended to be run internally for now?

**Comment by mhanratty** [comment]
we are open for feedback @jdittrich :)
