### ISSUE TITLE
Create welcome message for community-ux@mozilla.org email list

### ISSUE THREAD

**Issue by mhanratty** [mozilla/community-ux#2]

**Comment by lco** [comment]
v1 is done. Here's the message:

> Hello, and welcome to the mailing list for Mozilla UX contributors! We're excited to have you here. For more information about becoming a UX contributor, see our wiki page: https://wiki.mozilla.org/UX/Community
> 
> We still have lots of work to do to get up and running, so please bear with us as we get organized :)

I plan to create a v2 with a link to the community participation guidelines.
