### ISSUE TITLE
Go through Madhava's new hire email and put into wiki

### ISSUE THREAD

**Issue by vtsatskin** [mozilla/community-ux#20]
# Madhava's Email

Also: we have a wiki page specifically for UX hires now: https://intranet.mozilla.org/UX/New_Hires

Resources:
- General 
  - https://intranet.mozilla.org/Main_Page
  - https://intranet.mozilla.org/New_Hire_Info
  - Lunch/food around the office: https://etherpad.mozilla.org/YBQZHA4auC
  - Mozilla Yammer instance: https://www.yammer.com/mozilla.com/
  - Phonebook (including org chart): https://phonebook.mozilla.org/
  - Making coffee on the Epoca (AKA "The Precious"): http://www.youtube.com/watch?v=6gykuptYAh0
  - Vidyo web client -- v.mozilla.com - log in with ldap
  - Book on "Producing Open Source Software" (section 6 - communications, in particular): http://producingoss.com/en/index.html
- IT
  - https://intranet.mozilla.org/New_Hire_IT_Guide
  - https://intranet.mozilla.org/New_Hire_IT_Checklist
  - it's called out in the above, but for extra emphasis -- set up backups and encrypt your laptop
  - Page for opening IT request bugs: https://bugzilla.mozilla.org/enter_bug.cgi?product=mozilla.org&format=itrequest
- HR
  - About 1-on-1s at Mozilla: https://intranet.mozilla.org/1_on_1%27s
  - Level (band) descriptions: https://intranet.mozilla.org/Level_Descriptions (blank for now, it seems - I have my own set)
  - PTO app: https://intranet.mozilla.org/pto/
- About using Bugzilla
  - http://bugzilla.mozilla.org
  - Good introductory overview: http://people.mozilla.org/~johnath/bugzilla/BugzillaForHumans.ogv
  - Hader-core tricks: http://bugzillatips.wordpress.com/2010/06/03/quicksearch-video/
  - Install this - Bugzilla Tweaks add-on: https://addons.mozilla.org/en-us/firefox/addon/bugzillajs/?src=search
- User-experience
  - Mozilla UX Blog: https://blog.mozilla.org/ux/
  - Firefox-ux team etherpad: http://firefox-ux.etherpad.mozilla.org/
  - Design Values Booklet - http://cl.ly/0E0Y210H2t46
  - There's a Dropbox share -- see below
- First-week things to do (many of these are covered in various of the above checklists):
  - edit your entry in the phonebook - https://ldap.mozilla.org/phonebook/  (see edit my entry link)
  - install an IRC client (colloquy) and register your nick (instructions above)
  - some channels: #ux, #ur, #mobile, #fx-team, #fistbump
  - Create a work flickr account, if you want to -- you can expense a pro account
  - install skitch, cloud.app, or both!
  - open an IT bug to get Adobe Suite
  - open an IT bug to get an android phone OR buy and expense one
  - create an egencia account (travel)
  - create a Expensify (also Bill.com, unless it's been done for you) account (expenses)
  - create a mozilla blog (or use your own) and get it connected to planet.mozilla.org
  - make sure Madhava books a 1:1 with you - http://www.dria.org/wordpress/archives/2010/02/25/1443/
- Weekly updates
  - Instead of a round-the-table weekly status meeting, we do it asynchronously by email.
  - On Mondays, just send me an email with:
    - What did you do last week
    - What are you going to do this week
    - Need help / getting blocked by anything?
- Recurring Meetings
  - Monday
    - [11am PST / 2pm EST] Mozilla project meeting https://wiki.mozilla.org/WeeklyUpdates
  - Tuesday
    - [10am PST / 1pm EST] Firefox Desktop development status meeting
    - [11am PST / 2pm EST] Firefox UX design critique session - https://firefox-ux.etherpad.mozilla.org/tuesdaycrit
  - Wednesday
    - [9:30am PST / 12:30pm EST] Mobile development status meeting https://wiki.mozilla.org/Mobile/Notes
    - [11am PST / 2pm EST] Firefox Product Call (OPTIONAL - as interested, only)
  - Thursday
    - [11am PST / 2pm EST] UX Show & Tell (OPTIONAL - as your time permits, or as you need feedback)

**Comment by mhanratty** [comment]
Hmmm....a lot of this looks staff specific and not really helpful for contributors. I do like the Bugzilla resources though. That could certainly be helpful for community newbies.

**Comment by vtsatskin** [comment]
Yeah a lot of it is, however I'm sure there's plenty to pick out.

**Comment by lco** [comment]
In case you didn't already know, here's the link to the wiki page I created for community: https://wiki.mozilla.org/UX/Community

@vtsatskin, I think you automatically get edit priviledges if you log in, but let someone in IT know if you can't edit it (or maybe I can give it to you?)
