### ISSUE TITLE
needs of contributors

### ISSUE THREAD

**Issue by jdittrich** [mozilla/community-ux#22]
In the brainstorming (notes/brainstorming.md) is a list of possible contributors. It might be very useful to try to find out why they want to be part of the Mozilla UX community – basically what their needs are (or at least educatedly guess it)

If such info comes up: Should that be added to the brainstorming.md or is that file for documentation purposes?

**Comment by vtsatskin** [comment]
Thanks for opening this issue!

Let's put the answers to this question in a separate document such as `notes/users.md`. The `notes/brainstorming.md` document is intended to document what we talked about in the meeting.

If we are making a pull-request for this, please use [hub](https://github.com/github/hub) to convert this issue into a pull-request to reduce the number of open issues and keep everything together. The syntax in our case would be:

```
hub pull-request -i <issue number> -b <base branch> -h <head branch>
```
