### ISSUE TITLE
Create a UX Bootcamp for contributors (like the one for webdevs?)

### ISSUE THREAD

**Issue by mhanratty** [mozilla/community-ux#4]
Our illustrious intern @vtsatskin suggested we make documentation for UX contributors like the one for Mozilla webdev contributors here: http://mozweb.readthedocs.org/en/latest/ 

Maybe similar to what we were talking about for UX professionals @ezoehunt ?

**Comment by vtsatskin** [comment]
Possible things I would like on a bootcamp:
- Our design values
- Our processes
  - Taking a design from concept to implemenation
  - Getting user feedback/research early
- Tools we use (e.g. photoshop, balsamiq, etc)
  - I don't know if we've standardized these.
- Where to find user research
  - How to get your own research
- Finding metrics
- Where to find current projects and work being done
  - Status board
  - Bugzilla
  - How to give feedback 
- How to use bugzilla for UX work
- Where to find design resources
  - Australis
  - Other projects I can't think of right now
- Current UX people at Mozilla
  - what they do/responsible for
  - How to contact them and get involved in their projects

Some of these things might not actually be things we have defined/gathered yet, so through trying to do this for the community, we may actually help our own processes. For example I'm not really sure where all our design resources are. Gathering the existing resources and putting a system/process in place that ensures new work done will always add to this basin of resources should be a side-effect that occurs from working on that section.

@mhanratty For the ones you think make sense to include in the bootcamp, we should make separate issues and perhaps tag them with a "bootcamp" tag.

**Comment by mhanratty** [comment]
Thanks @vtsatskin One thing I think would be cool with the tools section is to identify people on the UX team who are particularly good with a tool. For example, @pwalm is a pro at Illustrator and Michael Maslaney is the Sketch guru.

**Comment by pwalm** [comment]
Wapow! _flings about Illustrator nunchucks_

Great list, @vtsatskin.

**Comment by vtsatskin** [comment]
Some other things that would be nice:
- How to find a reviewer for your design
  - More specifically, who is the best reviewer for each component/project
- How to get feedback for designs in general (mailing lists? wiki? irc?)

**Comment by jdittrich** [comment]
The [UX community page of Libre Office](https://www.libreoffice.org/community/design/) is worth a look for inspiration (some time ago I informally reviewed UX-Community Pages of FLOSS Projects). It is not a typical bootcamp structure though.
