### ISSUE TITLE
Create design brief for contributor projects

### ISSUE THREAD

**Issue by mhanratty** [mozilla/community-ux#6]
Here is a rough draft of a design brief for contributor projects--something we could use for student projects that require mentorship and projects that are larger in scope and timeline. 

https://docs.google.com/a/mozilla.com/document/d/1ylyIkqrHCW01-Xt-5SGO96TPd2njREDDQOJArpkMIH8/edit

**Comment by vtsatskin** [comment]
What is the intended purpose of coming up with filling out one of these design briefs? One answer I can think of is: making a new contributor aware of the various things to consider when designing. Is this correct?

I could see someone new struggling to fill in some of these pieces of information (e.g. technical constraints). I wouldn't want this to be a barrier to contributions (i.e. think filling your own taxes). I think it will be important to consider how contributors will go about asking for help and feedback on sections they may not be able to answer. 

Overall looks pretty awesome.

**Comment by ezoehunt** [comment]
Love design briefs. But similar to @vtsatskin I wonder if this is a lot for a contributer to tackle on their own. For longer-term projects, I'm imagining that an internal UX person is a mentor who works with the contributer to determine which deliverables are applicable to the design problem. More of a team working together than a contributer working alone. Thoughts?

**Comment by mhanratty** [comment]
Ah yes. I did not intend the _contributor_ to fill in the design brief but rather the mentor to fill it in. The design brief template is meant as a resource for the mentor. I agree with @ezoehunt that the mentor should work with the contributor to determine the deliverables and milestones--this is just a starting point and guide. It's like a checklist to help make sure the mentor has thought through the project and is giving the contributor enough information to be successful.

**Comment by jdittrich** [comment]
A _design brief template_ I a great idea. 
Should the template include a range of possible points to consider (out of which some are selected) or is this a suggested basic design process?
