### ISSUE TITLE
Get UX Marketplace contributor stuff ready for May 8th Marketplace Day

### ISSUE THREAD

**Issue by mhanratty** [mozilla/community-ux#7]
Marketplace Community Manager Amy Tsay has planned a "Marketplace Day" on Thursday, May 8th to try to bring more contributors into the project. 

https://etherpad.mozilla.org/marketplace-day

I hope we can have some stuff ready for any UX contributors who might come. I'm thinking at a minimum we could have our "goodfirstbugs" list groomed and ready:

This link does not work: https://bugzilla.mozilla.org/buglist.cgi?cmdtype=dorem&remaction=run&namedcmd=Marketplace%20goodfirstbug&list_id=9958427

This link works: https://bugzilla.mozilla.org/buglist.cgi?cmdtype=dorem&remaction=run&namedcmd=Marketplace%20goodfirstbug&sharer_id=453984&list_id=10081714

What do you think: @pwalm @tsmuse @ezoehunt @brampitoyo

**Comment by pwalm** [comment]
This is great. The first thing that jumps to mind is a 404 page. I'll think on some others...

**Comment by pwalm** [comment]
Oh, maybe background patterns for the Feed v2 stuff?

**Comment by mhanratty** [comment]
Here is the etherpad page for UX contributors for the Marketplace Day on Thursday, May 8th:
https://etherpad.mozilla.org/mp-test-day-ux-05082014
