### ISSUE TITLE
Create list of all the UX'ers at Mozilla and post in wiki

### ISSUE THREAD

**Issue by mhanratty** [mozilla/community-ux#9]
Would be helpful to the community (both internal + external) if we had a list of all the nice UX'ers at Mozilla. @ryanfeeley I remember you putting something like this together a few months back. Would you be cool doing this? Can we include Mocos + Mofos?

**Comment by ryanfeeley** [comment]
Like this old one? https://www.dropbox.com/s/aiebyxc32z62q5w/mozilla-ux.html

I'd be game for this! Here's a deal: you get me the row and column headings and I'll track down the people.

**Comment by mhanratty** [comment]
I imagine this will live in on the UX wiki. I like how the FFOS team has their UX Team Contact Information set up:
https://wiki.mozilla.org/Gaia/UXTeam

Headings
• Name
• Role
• Product/Org (Identity, Marketplace, etc.)
• link to Mozillians profile (like this: https://mozillians.org/en-US/u/mhanratty/)

I should say, I am afraid that the team list will get stale, so I'm also up for just linking to the team list for each product.
